#!/usr/bin/env ruby
# frozen_string_literal: true

require "json"
require "toon_fu"

input = $stdin.read

puts(begin
  ToonFu.encode(JSON.parse(input))
rescue JSON::ParserError, ToonFu::Error
  input
end)
